version: "3"
services:
  blog:
    image: 3e25031f8af8
    ports:
      - "8080:8080"
    networks:
      - mariadb-nw
    depends_on:
      - mariadb


  mariadb:
    image: mariadb
    networks:
      - mariadb-nw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=myDB

networks:
  mariadb-nw:
